kind: pipeline
name: default

steps:
  - name: greeting
    image: alpine
    commands:
    - echo hello
    - ls -lah
    - ls -lah deploy
    - pwd
    - docker images

  - name: build
    image: plugins/docker    
    settings:
      dockerfile: ./deploy/Dockerfile
      context: ./deploy/
      tags:
      - latest

  - name: after
    image: alpine
    commands:
    - docker ps -a
    - docker images
