kind: pipeline
name: default

steps:
  - name: greeting
    image: alpine
    commands:
    - echo hello
    - ls -lah
    - ls -lah deploy
    - pwd

  - name: build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - cd deploy
      - docker build -t jserver .

  - name: after
    image: alpine
    commands:
    - docker ps -a
    - docker images

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - master
  event:
    - push
