kind: pipeline
name: default

steps:
  - name: greeting
    image: alpine
    commands:
    - echo hello
    - ls -lah
    - ls -lah deploy
    - pwd

  - name: build
    image: docker
    commands:
      - cd deploy
      - docker build -t jserver .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: after
    image: alpine
    commands:
    - docker ps -a
    - docker images
