kind: pipeline
name: default

steps:
  - name: greeting
    image: alpine
    commands:
    - echo hello
    - ls -lah
    - ls -lah deploy
    - pwd

  - name: build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    environment:
        DEPLOY_HOST:
          from_secret: DEPLOY_HOST
    commands:
      - sleep 10 # give docker enough time to initialize
      - cd deploy
      - docker build -t bashhello .
      - docker ps -a
      - docker images
      - docker save bashhello | bzip2 | ssh root@$DEPLOY_HOST docker load

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - master
  event:
    - push
